using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace UnambitiousFx.Synapse.Generator.Analyzers;

internal enum HandlerKind
{
    Request,
    RequestWithResponse,
    Event,
    Stream
}

internal readonly struct MessageInterface
{
    public MessageInterface(HandlerKind kind, ITypeSymbol messageType)
    {
        Kind = kind;
        MessageType = messageType;
    }

    public HandlerKind Kind { get; }

    public ITypeSymbol MessageType { get; }
}

/// <summary>
///     Symbol lookups shared by the Synapse analyzers. Everything is matched by name in the Abstractions
///     namespace so the analyzers work against any version of the package.
/// </summary>
internal static class SynapseSymbols
{
    public const string AbstractionsNamespace = "UnambitiousFx.Synapse.Abstractions";
    public const string AbstractionsAssemblyName = "UnambitiousFx.Synapse.Abstractions";

    public static bool ReferencesSynapse(Compilation compilation)
    {
        return compilation.GetTypesByMetadataName($"{AbstractionsNamespace}.IRequest").Length > 0;
    }

    /// <summary>
    ///     Whether the tree is generated code: a conventional generated file name or an auto-generated header. The
    ///     analyzers still read generated code for facts (handlers may be generated) but never report on it.
    /// </summary>
    public static bool IsGenerated(SyntaxTree tree, CancellationToken cancellationToken)
    {
        var path = tree.FilePath;
        if (path.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || path.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase)
            || path.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
            || path.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        foreach (var trivia in tree.GetRoot(cancellationToken).GetLeadingTrivia())
        {
            if (trivia.IsKind(SyntaxKind.SingleLineCommentTrivia) || trivia.IsKind(SyntaxKind.MultiLineCommentTrivia))
            {
                var text = trivia.ToString();
                if (text.IndexOf("<auto-generated", StringComparison.OrdinalIgnoreCase) >= 0
                    || text.IndexOf("<autogenerated", StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    return true;
                }
            }
        }

        return false;
    }

    /// <summary>The first location of the symbol that is in hand-written source, or null when there is none.</summary>
    public static Location? GetReportableLocation(ISymbol symbol, CancellationToken cancellationToken)
    {
        return symbol.Locations.FirstOrDefault(location =>
            location.IsInSource && !IsGenerated(location.SourceTree!, cancellationToken));
    }

    public static bool IsInAbstractions(ISymbol symbol)
    {
        return symbol.ContainingNamespace?.ToDisplayString() == AbstractionsNamespace;
    }

    public static bool IsAttribute(INamedTypeSymbol? attributeClass, string attributeName)
    {
        return attributeClass is not null && attributeClass.Name == attributeName && IsInAbstractions(attributeClass);
    }

    public static bool IsHandlerAttribute(INamedTypeSymbol? attributeClass)
    {
        return IsAttribute(attributeClass, "RequestHandlerAttribute")
               || IsAttribute(attributeClass, "EventHandlerAttribute")
               || IsAttribute(attributeClass, "StreamRequestHandlerAttribute");
    }

    public static bool HasHandlerAttribute(ISymbol symbol)
    {
        return symbol.GetAttributes().Any(attribute => IsHandlerAttribute(attribute.AttributeClass));
    }

    public static MessageInterface? GetHandlerInterface(INamedTypeSymbol iface)
    {
        if (!IsInAbstractions(iface))
        {
            return null;
        }

        return iface.MetadataName switch
        {
            "IRequestHandler`1" => new MessageInterface(HandlerKind.Request, iface.TypeArguments[0]),
            "IRequestHandler`2" => new MessageInterface(HandlerKind.RequestWithResponse, iface.TypeArguments[0]),
            "IEventHandler`1" => new MessageInterface(HandlerKind.Event, iface.TypeArguments[0]),
            "IStreamRequestHandler`2" => new MessageInterface(HandlerKind.Stream, iface.TypeArguments[0]),
            _ => null
        };
    }

    public static bool IsRequestInterface(INamedTypeSymbol iface)
    {
        return IsInAbstractions(iface) && iface.MetadataName is "IRequest" or "IRequest`1";
    }

    public static MessageInterface? GetBehaviorInterface(INamedTypeSymbol iface)
    {
        if (!IsInAbstractions(iface))
        {
            return null;
        }

        return iface.MetadataName switch
        {
            "IRequestPipelineBehavior`1" => new MessageInterface(HandlerKind.Request, iface.TypeArguments[0]),
            "IRequestPipelineBehavior`2" =>
                new MessageInterface(HandlerKind.RequestWithResponse, iface.TypeArguments[0]),
            "IEventPipelineBehavior`1" => new MessageInterface(HandlerKind.Event, iface.TypeArguments[0]),
            "IStreamRequestPipelineBehavior`2" => new MessageInterface(HandlerKind.Stream, iface.TypeArguments[0]),
            _ => null
        };
    }

    public static IEnumerable<INamedTypeSymbol> GetTypes(INamespaceSymbol root, CancellationToken cancellationToken)
    {
        foreach (var member in root.GetMembers())
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (member is INamespaceSymbol child)
            {
                foreach (var type in GetTypes(child, cancellationToken))
                {
                    yield return type;
                }
            }
            else if (member is INamedTypeSymbol named)
            {
                yield return named;
                foreach (var nested in GetNested(named))
                {
                    yield return nested;
                }
            }
        }
    }

    private static IEnumerable<INamedTypeSymbol> GetNested(INamedTypeSymbol type)
    {
        foreach (var nested in type.GetTypeMembers())
        {
            yield return nested;
            foreach (var deeper in GetNested(nested))
            {
                yield return deeper;
            }
        }
    }

    public static bool ContainsTypeParameter(ITypeSymbol type)
    {
        return type switch
        {
            ITypeParameterSymbol => true,
            INamedTypeSymbol named => named.TypeArguments.Any(ContainsTypeParameter),
            IArrayTypeSymbol array => ContainsTypeParameter(array.ElementType),
            _ => false
        };
    }
}
