<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <InvariantGlobalization>true</InvariantGlobalization>
        <PublishAot>true</PublishAot>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Synapse.AspNetCore\Synapse.AspNetCore.csproj" />
        <ProjectReference Include="..\..\src\Synapse\Synapse.csproj" />
        <ProjectReference Include="..\..\src\Synapse.Generator\Synapse.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\MinimalApi.Counter\MinimalApi.Counter.csproj" />
    </ItemGroup>

</Project>
