<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove(&#39;build.props&#39;))" />

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <IsPackable>false</IsPackable>
        <WarningsAsErrors>false</WarningsAsErrors>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
        <WarningsAsErrors>$(WarningsAsErrors);SYN101;SYN102;SYN103;SYN104</WarningsAsErrors>
        <RootNamespace>$(Product).Examples.$(MSBuildProjectName)</RootNamespace>
        <AssemblyName>$(Product).Examples.$(MSBuildProjectName)</AssemblyName>
    </PropertyGroup>
</Project>
