using System.Text;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using UnambitiousFx.Synapse.Endpoints.Generator.Model;

namespace UnambitiousFx.Synapse.Endpoints.Generator.Emit;

/// <summary>
///     Renders <c>SynapseEndpointBinders.g.cs</c>: one <c>IEndpointBinder&lt;T&gt;</c> implementation
///     per distinct bound type, each assigning route, query, header and body values directly onto the
///     message's properties. Direct assignment (rather than reflection) is what keeps request binding
///     reflection-free and AOT-safe at runtime.
/// </summary>
internal static class BinderEmitter
{
    private const string BindingNamespace = "global::UnambitiousFx.Synapse.Endpoints.Binding";

    internal static SourceText Emit(string rootNamespace,
        (string TypeFullName, EquatableArray<BindablePropertyModel> Properties, bool IsBodylessVerb)[] boundTypes)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine($"namespace {rootNamespace};");

        foreach (var (typeFullName, properties, isBodylessVerb) in boundTypes)
        {
            builder.AppendLine();
            EmitBinder(builder, typeFullName, properties, isBodylessVerb);
        }

        return SourceText.From(builder.ToString(), Encoding.UTF8);
    }

    /// <summary>
    ///     Computes the generated binder class name for a bound type. Exposed so the registration
    ///     module initializer (emitted separately) can construct matching <c>new ...Binder()</c>
    ///     expressions.
    /// </summary>
    internal static string GetBinderClassName(string typeFullName)
    {
        var name = typeFullName.StartsWith("global::", StringComparison.Ordinal)
            ? typeFullName.Substring("global::".Length)
            : typeFullName;

        var builder = new StringBuilder(name.Length + 6);

        foreach (var c in name)
        {
            builder.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        }

        builder.Append("Binder");
        return builder.ToString();
    }

    private static void EmitBinder(StringBuilder builder,
        string typeFullName,
        EquatableArray<BindablePropertyModel> properties,
        bool isBodylessVerb)
    {
        var className = GetBinderClassName(typeFullName);

        var hasBodyProperty = false;
        foreach (var property in properties)
        {
            if (property.Source == BindingSource.Body)
            {
                hasBodyProperty = true;
                break;
            }
        }

        // Skip reading the body only when the verb never carries one AND nothing resolved to Body
        // (an explicit [FromBody] can still force a body read even on a bodyless verb).
        var isBodyless = isBodylessVerb && !hasBodyProperty;

        builder.AppendLine(
            $"internal sealed class {className} : {BindingNamespace}.IEndpointBinder<{typeFullName}>");
        builder.AppendLine("{");
        builder.AppendLine(
            $"    public async global::System.Threading.Tasks.ValueTask<{BindingNamespace}.BindResult<{typeFullName}>> BindAsync(");
        builder.AppendLine("        global::Microsoft.AspNetCore.Http.HttpContext context)");
        builder.AppendLine("    {");

        if (isBodyless)
        {
            builder.AppendLine($"        var message = new {typeFullName}();");
        }
        else
        {
            builder.AppendLine(
                $"        var body = await {BindingNamespace}.BindingHelpers.ReadJsonBodyAsync<{typeFullName}>(context);");
            builder.AppendLine("        if (!body.IsSuccess)");
            builder.AppendLine("        {");
            builder.AppendLine(
                $"            return {BindingNamespace}.BindResult<{typeFullName}>.Failure(body.Error!);");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        var message = body.Value!;");
        }

        foreach (var property in properties)
        {
            if (property.Source == BindingSource.Body)
            {
                continue;
            }

            builder.AppendLine();
            EmitPropertyBinding(builder, typeFullName, property);
        }

        builder.AppendLine();
        builder.AppendLine($"        return {BindingNamespace}.BindResult<{typeFullName}>.Success(message);");
        builder.AppendLine("    }");
        builder.AppendLine("}");
    }

    private static void EmitPropertyBinding(StringBuilder builder,
        string typeFullName,
        BindablePropertyModel property)
    {
        var tryGetMethod = property.Source switch
        {
            BindingSource.Route => "TryGetRoute",
            BindingSource.Query => "TryGetQuery",
            BindingSource.Header => "TryGetHeader",
            _ => throw new InvalidOperationException($"Unexpected binding source '{property.Source}'.")
        };

        var sourceLabel = DescribeSource(property.Source);

        var sourceKeyLiteral = SymbolDisplay.FormatLiteral(property.SourceKey, quote: true);
        var rawVariable = "raw" + property.Name;
        var missingMessage =
            SymbolDisplay.FormatLiteral($"{sourceLabel} value '{property.SourceKey}' is missing.", quote: true);

        if (property.IsNullable)
        {
            builder.AppendLine(
                $"        if ({BindingNamespace}.BindingHelpers.{tryGetMethod}(context, {sourceKeyLiteral}, out var {rawVariable}))");
            builder.AppendLine("        {");
            EmitParseAndAssign(builder, "            ", typeFullName, property, rawVariable);
            builder.AppendLine("        }");
        }
        else
        {
            builder.AppendLine(
                $"        if (!{BindingNamespace}.BindingHelpers.{tryGetMethod}(context, {sourceKeyLiteral}, out var {rawVariable}))");
            builder.AppendLine("        {");
            builder.AppendLine(
                $"            return {BindingNamespace}.BindResult<{typeFullName}>.Failure({missingMessage});");
            builder.AppendLine("        }");
            builder.AppendLine();
            EmitParseAndAssign(builder, "        ", typeFullName, property, rawVariable);
        }
    }

    private static void EmitParseAndAssign(StringBuilder builder,
        string indent,
        string typeFullName,
        BindablePropertyModel property,
        string rawVariable)
    {
        string valueExpression;

        if (property.IsString)
        {
            valueExpression = property.IsNullable ? rawVariable : rawVariable + "!";
        }
        else
        {
            var valueVariable = "value" + property.Name;
            var propertyDisplayTypeName = property.TypeFullName.StartsWith("global::", StringComparison.Ordinal)
                ? property.TypeFullName.Substring("global::".Length)
                : property.TypeFullName;
            var notAValidMessage = SymbolDisplay.FormatLiteral(
                $"{DescribeSource(property.Source)} value '{property.SourceKey}' is not a valid {propertyDisplayTypeName}.",
                quote: true);

            var tryParseExpression = property.IsEnum
                ? $"global::System.Enum.TryParse<{property.TypeFullName}>({rawVariable}, out var {valueVariable})"
                : $"{property.TypeFullName}.TryParse({rawVariable}, out var {valueVariable})";

            builder.AppendLine($"{indent}if (!{tryParseExpression})");
            builder.AppendLine($"{indent}{{");
            builder.AppendLine(
                $"{indent}    return {BindingNamespace}.BindResult<{typeFullName}>.Failure({notAValidMessage});");
            builder.AppendLine($"{indent}}}");
            builder.AppendLine();

            valueExpression = valueVariable;
        }

        var propertyName = EscapeIdentifier(property.Name);
        builder.AppendLine(property.IsRecordWith
            ? $"{indent}message = message with {{ {propertyName} = {valueExpression} }};"
            : $"{indent}message.{propertyName} = {valueExpression};");
    }

    /// <summary>
    ///     A symbol's bare <c>Name</c> (unlike <see cref="SymbolDisplay" /> output) is never escaped,
    ///     so a property legitimately named after a reserved word (declared as <c>@class</c>, say)
    ///     would otherwise be emitted as an unescaped keyword and fail to compile.
    /// </summary>
    private static string EscapeIdentifier(string name)
    {
        return SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None ||
               SyntaxFacts.GetContextualKeywordKind(name) != SyntaxKind.None
            ? "@" + name
            : name;
    }

    private static string DescribeSource(BindingSource source)
    {
        return source switch
        {
            BindingSource.Route => "Route",
            BindingSource.Query => "Query",
            BindingSource.Header => "Header",
            _ => throw new InvalidOperationException($"Unexpected binding source '{source}'.")
        };
    }
}
