using System.Text;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using UnambitiousFx.Synapse.Endpoints.Generator.Model;

namespace UnambitiousFx.Synapse.Endpoints.Generator.Emit;

/// <summary>
///     Renders <c>SynapseEndpointBinders.g.cs</c>: one <c>IEndpointBinder&lt;T&gt;</c> implementation
///     per distinct bound type, each assigning route, query, header and body values directly onto the
///     message's properties. Direct assignment (rather than reflection) is what keeps request binding
///     reflection-free and AOT-safe at runtime.
/// </summary>
internal static class BinderEmitter
{
    private const string BindingNamespace = "global::UnambitiousFx.Synapse.Endpoints.Binding";

    internal static SourceText Emit(string rootNamespace,
        BoundTypeInfo[] boundTypes)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine($"namespace {rootNamespace};");

        foreach (var boundType in boundTypes)
        {
            builder.AppendLine();
            EmitBinder(builder, boundType);
        }

        return SourceText.From(builder.ToString(), Encoding.UTF8);
    }

    /// <summary>
    ///     Computes the generated binder class name for a bound type. Exposed so the registration
    ///     module initializer (emitted separately) can construct matching <c>new ...Binder()</c>
    ///     expressions.
    /// </summary>
    internal static string GetBinderClassName(string typeFullName)
    {
        var name = typeFullName.StartsWith("global::", StringComparison.Ordinal)
            ? typeFullName.Substring("global::".Length)
            : typeFullName;

        var builder = new StringBuilder(name.Length + 6);

        foreach (var c in name)
        {
            builder.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        }

        builder.Append("Binder");
        return builder.ToString();
    }

    private static void EmitBinder(StringBuilder builder,
        BoundTypeInfo boundType)
    {
        var typeFullName = boundType.TypeFullName;
        var properties = boundType.Properties;
        var className = GetBinderClassName(typeFullName);

        var hasBodyProperty = false;
        foreach (var property in properties)
        {
            if (property.Source == BindingSource.Body)
            {
                hasBodyProperty = true;
                break;
            }
        }

        // Skip reading the body only when the verb never carries one AND nothing resolved to Body
        // (an explicit [FromBody] can still force a body read even on a bodyless verb).
        var isBodyless = boundType.IsBodylessVerb && !hasBodyProperty;

        builder.AppendLine(
            $"internal sealed class {className} : {BindingNamespace}.IEndpointBinder<{typeFullName}>");
        builder.AppendLine("{");
        builder.AppendLine(
            $"    public async global::System.Threading.Tasks.ValueTask<{BindingNamespace}.BindResult<{typeFullName}>> BindAsync(");
        builder.AppendLine("        global::Microsoft.AspNetCore.Http.HttpContext context)");
        builder.AppendLine("    {");

        var consumedByConstructor = new HashSet<string>(StringComparer.Ordinal);

        if (isBodyless)
        {
            if (boundType.HasParameterlessConstructor)
            {
                builder.AppendLine($"        var message = new {typeFullName}();");
            }
            else
            {
                EmitPrimaryConstructorCall(builder, typeFullName, properties, boundType.PrimaryConstructorParameters,
                    consumedByConstructor);
            }
        }
        else
        {
            builder.AppendLine(
                $"        var body = await {BindingNamespace}.BindingHelpers.ReadJsonBodyAsync<{typeFullName}>(context);");
            builder.AppendLine("        if (!body.IsSuccess)");
            builder.AppendLine("        {");
            builder.AppendLine(
                $"            return {BindingNamespace}.BindResult<{typeFullName}>.Failure(body.Error!);");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        var message = body.Value!;");
        }

        foreach (var property in properties)
        {
            if (property.Source == BindingSource.Body || consumedByConstructor.Contains(property.Name))
            {
                continue;
            }

            builder.AppendLine();
            EmitPropertyBinding(builder, typeFullName, property);
        }

        builder.AppendLine();
        builder.AppendLine($"        return {BindingNamespace}.BindResult<{typeFullName}>.Success(message);");
        builder.AppendLine("    }");
        builder.AppendLine("}");
    }

    /// <summary>
    ///     Emits the argument-computing statements for every parameter of the type's primary
    ///     constructor, followed by the <c>var message = new T(...)</c> call itself. A parameter
    ///     matched to a bound property (by name, case-insensitively) is parsed and validated before
    ///     construction rather than after — the object does not exist yet, so a <c>with</c>
    ///     expression is not an option here. A parameter with no matching property (never resolved as
    ///     bindable at all, or resolved but omitted for having no viable <c>TryParse</c>, Task 17's
    ///     SYNE012) is passed a literal default value: <c>default!</c> for a reference type, so the
    ///     null-forgiving operator suppresses the nullable-reference warning that bare <c>default</c>
    ///     would otherwise raise on the generated code (a real defect fixed in Task 17 —
    ///     <c>AssertGeneratedCompiles</c> only fails on <c>Error</c>-severity diagnostics, so this
    ///     warning previously went unnoticed by the test suite even though a consumer building with
    ///     warnings-as-errors would fail); bare <c>default</c> for a value type, where it needs no
    ///     suppression.
    /// </summary>
    private static void EmitPrimaryConstructorCall(StringBuilder builder,
        string typeFullName,
        EquatableArray<BindablePropertyModel> properties,
        EquatableArray<ConstructorParameterModel> parameters,
        HashSet<string> consumedByConstructor)
    {
        var propertyByName = new Dictionary<string, BindablePropertyModel>(StringComparer.OrdinalIgnoreCase);
        foreach (var property in properties)
        {
            propertyByName[property.Name] = property;
        }

        var argumentExpressions = new List<string>();

        foreach (var parameter in parameters)
        {
            // A bound type reaches this method only when it is bodyless (see EmitBinder), which
            // guarantees no property here resolved to Body — every match is Route/Query/Header.
            if (propertyByName.TryGetValue(parameter.Name, out var property))
            {
                argumentExpressions.Add(EmitConstructorArgumentBinding(builder, typeFullName, property));
                consumedByConstructor.Add(property.Name);
            }
            else
            {
                argumentExpressions.Add(parameter.IsReferenceType ? "default!" : "default");
            }
        }

        builder.AppendLine($"        var message = new {typeFullName}({string.Join(", ", argumentExpressions)});");
    }

    /// <summary>
    ///     Emits the statements needed to compute one constructor argument and returns the expression
    ///     to pass for it. A non-nullable value is validated the same way as a post-construction
    ///     assignment (missing or unparsable is a bind failure); a nullable value cannot simply be
    ///     "skipped" the way a post-construction assignment can, because the constructor call still
    ///     needs *some* argument, so it is pre-declared with a default and conditionally overwritten.
    /// </summary>
    private static string EmitConstructorArgumentBinding(StringBuilder builder,
        string typeFullName,
        BindablePropertyModel property)
    {
        var tryGetMethod = GetTryGetMethod(property.Source);
        var sourceKeyLiteral = SymbolDisplay.FormatLiteral(property.SourceKey, quote: true);
        var rawVariable = "raw" + property.Name;

        if (!property.IsNullable)
        {
            var missingMessage = SymbolDisplay.FormatLiteral(
                $"{DescribeSource(property.Source)} value '{property.SourceKey}' is missing.", quote: true);

            builder.AppendLine(
                $"        if (!{BindingNamespace}.BindingHelpers.{tryGetMethod}(context, {sourceKeyLiteral}, out var {rawVariable}))");
            builder.AppendLine("        {");
            builder.AppendLine(
                $"            return {BindingNamespace}.BindResult<{typeFullName}>.Failure({missingMessage});");
            builder.AppendLine("        }");

            return EmitParseCheckOnly(builder, "        ", typeFullName, property, rawVariable,
                "value" + property.Name);
        }

        var declaredType = property.TypeFullName + "?";
        var outerVariable = "value" + property.Name;

        builder.AppendLine($"        {declaredType} {outerVariable} = default;");
        builder.AppendLine(
            $"        if ({BindingNamespace}.BindingHelpers.{tryGetMethod}(context, {sourceKeyLiteral}, out var {rawVariable}))");
        builder.AppendLine("        {");

        var parsedExpression = EmitParseCheckOnly(builder, "            ", typeFullName, property, rawVariable,
            "parsed" + property.Name);
        builder.AppendLine($"            {outerVariable} = {parsedExpression};");
        builder.AppendLine("        }");

        return outerVariable;
    }

    private static void EmitPropertyBinding(StringBuilder builder,
        string typeFullName,
        BindablePropertyModel property)
    {
        var tryGetMethod = GetTryGetMethod(property.Source);
        var sourceLabel = DescribeSource(property.Source);

        var sourceKeyLiteral = SymbolDisplay.FormatLiteral(property.SourceKey, quote: true);
        var rawVariable = "raw" + property.Name;
        var missingMessage =
            SymbolDisplay.FormatLiteral($"{sourceLabel} value '{property.SourceKey}' is missing.", quote: true);

        if (property.IsNullable)
        {
            builder.AppendLine(
                $"        if ({BindingNamespace}.BindingHelpers.{tryGetMethod}(context, {sourceKeyLiteral}, out var {rawVariable}))");
            builder.AppendLine("        {");
            EmitParseAndAssign(builder, "            ", typeFullName, property, rawVariable);
            builder.AppendLine("        }");
        }
        else
        {
            builder.AppendLine(
                $"        if (!{BindingNamespace}.BindingHelpers.{tryGetMethod}(context, {sourceKeyLiteral}, out var {rawVariable}))");
            builder.AppendLine("        {");
            builder.AppendLine(
                $"            return {BindingNamespace}.BindResult<{typeFullName}>.Failure({missingMessage});");
            builder.AppendLine("        }");
            builder.AppendLine();
            EmitParseAndAssign(builder, "        ", typeFullName, property, rawVariable);
        }
    }

    private static void EmitParseAndAssign(StringBuilder builder,
        string indent,
        string typeFullName,
        BindablePropertyModel property,
        string rawVariable)
    {
        var valueExpression =
            EmitParseCheckOnly(builder, indent, typeFullName, property, rawVariable, "value" + property.Name);

        var propertyName = EscapeIdentifier(property.Name);
        builder.AppendLine(property.IsRecordWith
            ? $"{indent}message = message with {{ {propertyName} = {valueExpression} }};"
            : $"{indent}message.{propertyName} = {valueExpression};");
    }

    /// <summary>
    ///     Emits the <c>TryParse</c> check (and its early-return on failure) for a non-string
    ///     property, or nothing for a string one, and returns the expression holding the final value
    ///     — the raw string itself, or the freshly parsed value. Shared between assigning the value
    ///     onto an already-constructed message and computing a constructor argument before the
    ///     message exists.
    /// </summary>
    private static string EmitParseCheckOnly(StringBuilder builder,
        string indent,
        string typeFullName,
        BindablePropertyModel property,
        string rawVariable,
        string resultVariableName)
    {
        if (property.IsString)
        {
            return property.IsNullable ? rawVariable : rawVariable + "!";
        }

        var propertyDisplayTypeName = property.TypeFullName.StartsWith("global::", StringComparison.Ordinal)
            ? property.TypeFullName.Substring("global::".Length)
            : property.TypeFullName;
        var notAValidMessage = SymbolDisplay.FormatLiteral(
            $"{DescribeSource(property.Source)} value '{property.SourceKey}' is not a valid {propertyDisplayTypeName}.",
            quote: true);

        var tryParseExpression = property.IsEnum
            ? $"global::System.Enum.TryParse<{property.TypeFullName}>({rawVariable}, out var {resultVariableName})"
            : $"{property.TypeFullName}.TryParse({rawVariable}, out var {resultVariableName})";

        builder.AppendLine($"{indent}if (!{tryParseExpression})");
        builder.AppendLine($"{indent}{{");
        builder.AppendLine(
            $"{indent}    return {BindingNamespace}.BindResult<{typeFullName}>.Failure({notAValidMessage});");
        builder.AppendLine($"{indent}}}");
        builder.AppendLine();

        return resultVariableName;
    }

    /// <summary>
    ///     A symbol's bare <c>Name</c> (unlike <see cref="SymbolDisplay" /> output) is never escaped,
    ///     so a property legitimately named after a reserved word (declared as <c>@class</c>, say)
    ///     would otherwise be emitted as an unescaped keyword and fail to compile.
    /// </summary>
    private static string EscapeIdentifier(string name)
    {
        return SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None ||
               SyntaxFacts.GetContextualKeywordKind(name) != SyntaxKind.None
            ? "@" + name
            : name;
    }

    private static string GetTryGetMethod(BindingSource source)
    {
        return source switch
        {
            BindingSource.Route => "TryGetRoute",
            BindingSource.Query => "TryGetQuery",
            BindingSource.Header => "TryGetHeader",
            _ => throw new InvalidOperationException($"Unexpected binding source '{source}'.")
        };
    }

    private static string DescribeSource(BindingSource source)
    {
        return source switch
        {
            BindingSource.Route => "Route",
            BindingSource.Query => "Query",
            BindingSource.Header => "Header",
            _ => throw new InvalidOperationException($"Unexpected binding source '{source}'.")
        };
    }
}
