using System.Text;
using Microsoft.CodeAnalysis.Text;
using UnambitiousFx.Synapse.Endpoints.Generator.Model;

namespace UnambitiousFx.Synapse.Endpoints.Generator.Emit;

/// <summary>
///     Renders <c>EndpointGroup.g.cs</c> (the <c>IEndpointGroup</c> implementation that maps every
///     discovered endpoint) and <c>SynapseEndpointRegistrations.g.cs</c> (the module initializer that
///     registers each endpoint's route metadata).
/// </summary>
internal static class EndpointGroupEmitter
{
    internal static SourceText EmitGroup(string rootNamespace,
        EndpointTarget[] endpoints)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine($"namespace {rootNamespace};");
        builder.AppendLine();
        builder.AppendLine("/// <summary>Maps every Synapse endpoint declared in this assembly.</summary>");
        builder.AppendLine("public sealed class EndpointGroup : global::UnambitiousFx.Synapse.Endpoints.IEndpointGroup");
        builder.AppendLine("{");
        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine("    public void Map(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints)");
        builder.AppendLine("    {");

        foreach (var endpoint in endpoints)
        {
            builder.AppendLine($"        endpoints.MapEndpoint<{endpoint.EndpointFullName}>();");
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        return SourceText.From(builder.ToString(), Encoding.UTF8);
    }

    internal static SourceText EmitRegistrations(string rootNamespace,
        EndpointTarget[] endpoints)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine($"namespace {rootNamespace};");
        builder.AppendLine();
        builder.AppendLine("internal static class SynapseEndpointRegistrations");
        builder.AppendLine("{");
        builder.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("    internal static void Register()");
        builder.AppendLine("    {");

        foreach (var endpoint in endpoints)
        {
            var methods = endpoint.HttpMethod.Length == 0
                ? "global::System.Array.Empty<string>()"
                : $"new[] {{ \"{endpoint.HttpMethod}\" }}";

            var group = endpoint.GroupFullName is null
                ? string.Empty
                : $", typeof({endpoint.GroupFullName}), static () => new {endpoint.GroupFullName}()";

            builder.AppendLine(
                $"        global::UnambitiousFx.Synapse.Endpoints.Binding.EndpointRegistry.RegisterMetadata<{endpoint.EndpointFullName}>(");
            builder.AppendLine(
                $"            new global::UnambitiousFx.Synapse.Endpoints.EndpointMetadata({methods}, \"{endpoint.Route}\"{group}));");
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        return SourceText.From(builder.ToString(), Encoding.UTF8);
    }
}
