using System.Text;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using UnambitiousFx.Synapse.Endpoints.Generator.Model;

namespace UnambitiousFx.Synapse.Endpoints.Generator.Emit;

/// <summary>
///     Renders one endpoint's generated file: its class reopened as a partial, holding its route
///     metadata and — for the tiers whose binding is generated — the binding and the OpenAPI hooks.
/// </summary>
/// <remarks>
///     One file per endpoint, not one per bound type. Two endpoints binding the same message each
///     get their own binding resolved from their own route and verb, which is why SYNE013 no longer
///     exists — see the design at docs/superpowers/specs/2026-09-07-endpoint-partial-generation-design.md.
///     Emitted for every endpoint kind, including the hand-bound and free-form ones: they bind
///     themselves, but <c>SynapseEndpoint.CreateMetadata</c> is abstract, so every endpoint needs the
///     metadata override and therefore has to be reopenable. Abstract rather than a base
///     implementation returning empty metadata deliberately: a raw endpoint's route used to come from
///     the registry, so a silent empty fallback would have compiled and left
///     <c>[Get("/health")] HealthEndpoint : BoundEndpoint</c> with no route at all.
/// </remarks>
internal static class EndpointPartialEmitter
{
    private const string BindingNamespace = "global::UnambitiousFx.Synapse.Endpoints.Binding";
    private const string InternalNamespace = "global::UnambitiousFx.Synapse.Endpoints.Internal";
    private const string EndpointsNamespace = "global::UnambitiousFx.Synapse.Endpoints";

    /// <summary>The hint name for one endpoint's generated file.</summary>
    /// <param name="declaration">The endpoint's declaration.</param>
    /// <returns>A hint name unique within the compilation.</returns>
    /// <remarks>
    ///     Built from namespace, enclosing types and type name, so two same-named endpoints in
    ///     different namespaces do not collide. A generic endpoint does reach here: SYNE010 reports it
    ///     but does not remove the target, so the hint name and the reopened declaration both come out
    ///     at arity zero and the emitted partial does not match the endpoint. That is harmless only
    ///     because SYNE010 is an Error and has already failed the build; nothing here needs to
    ///     sanitise type-argument brackets, because the name never contains any.
    /// </remarks>
    internal static string HintName(EndpointDeclaration declaration)
    {
        var builder = new StringBuilder();

        if (declaration.Namespace.Length > 0)
        {
            builder.Append(declaration.Namespace).Append('.');
        }

        foreach (var enclosing in declaration.EnclosingTypes)
        {
            builder.Append(enclosing.Name).Append('.');
        }

        return builder.Append(declaration.TypeName).Append(".Synapse.g.cs").ToString();
    }

    /// <summary>Renders one endpoint's generated partial.</summary>
    /// <param name="endpoint">The endpoint to emit for.</param>
    /// <param name="boundType">
    ///     What it binds, and the properties resolved from its own route and verb, or
    ///     <see langword="null" /> for a kind whose binding is not generated — in which case only the
    ///     metadata override is emitted.
    /// </param>
    /// <returns>The generated source.</returns>
    internal static SourceText Emit(EndpointTarget endpoint,
        BoundTypeInfo? boundType)
    {
        var declaration = endpoint.Declaration;
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        if (declaration.Namespace.Length > 0)
        {
            builder.AppendLine($"namespace {declaration.Namespace};");
            builder.AppendLine();
        }

        // Each enclosing type is reopened with its own keyword: partial declarations of one type must
        // all use the same one (CS0261), so an endpoint nested inside a record or a struct cannot be
        // reopened with `partial class`.
        var indent = string.Empty;
        foreach (var enclosing in declaration.EnclosingTypes)
        {
            builder.AppendLine($"{indent}partial {enclosing.Keyword} {enclosing.Name}");
            builder.AppendLine($"{indent}{{");
            indent += "    ";
        }

        // The endpoint itself is always a class: discovery matches ClassDeclarationSyntax, and a
        // record could not derive from one of the base tiers anyway (CS8864).
        builder.AppendLine($"{indent}partial class {declaration.TypeName}");
        builder.AppendLine($"{indent}{{");

        // `sealed override` inside a sealed class is redundant; the modifier is omitted rather than
        // emitted and warned about.
        var modifier = declaration.IsSealed ? "override" : "sealed override";

        if (boundType is not null)
        {
            EmitBindAsync(builder, boundType, indent + "    ", modifier);
            EmitMetadata(builder, boundType, indent + "    ", modifier);
            builder.AppendLine();
        }

        EmitCreateMetadata(builder, endpoint, indent + "    ", modifier);

        builder.AppendLine($"{indent}}}");

        for (var i = 0; i < declaration.EnclosingTypes.Count; i++)
        {
            indent = indent.Substring(0, indent.Length - 4);
            builder.AppendLine($"{indent}}}");
        }

        return SourceText.From(builder.ToString(), Encoding.UTF8);
    }

    /// <summary>
    ///     Renders the <c>BindAsync</c> override, whose body <see cref="BinderEmitter" /> renders.
    /// </summary>
    private static void EmitBindAsync(StringBuilder builder,
        BoundTypeInfo boundType,
        string indent,
        string modifier)
    {
        builder.AppendLine($"{indent}/// <inheritdoc />");
        builder.AppendLine(
            $"{indent}public {modifier} async global::System.Threading.Tasks.ValueTask<{BindingNamespace}.BindResult<{boundType.TypeFullName}>> BindAsync(");
        builder.AppendLine($"{indent}    global::Microsoft.AspNetCore.Http.HttpContext context)");
        builder.AppendLine($"{indent}{{");

        BinderEmitter.EmitBindBody(builder, boundType, indent + "    ");

        builder.AppendLine($"{indent}}}");
    }

    /// <summary>
    ///     Renders the OpenAPI metadata hooks: the body kind the binding reads, and the parameter and
    ///     form-field lists it reads them from.
    /// </summary>
    /// <remarks>
    ///     <c>BoundBodyKind</c>, never <c>DeclaredRequestBody</c>: the verb narrowing that method
    ///     applies is resolved at startup, because an endpoint may declare its route — and therefore
    ///     its verb — inside <c>Configure</c>, which the generator cannot see.
    ///     <c>DeclaredParameters</c> and <c>DeclaredFormFields</c> are emitted only when there is
    ///     something to declare; the base implementations already return an empty list.
    /// </remarks>
    private static void EmitMetadata(StringBuilder builder,
        BoundTypeInfo boundType,
        string indent,
        string modifier)
    {
        builder.AppendLine();
        builder.AppendLine($"{indent}/// <inheritdoc />");
        builder.AppendLine(
            $"{indent}protected {modifier} {BindingNamespace}.RequestBodyKind BoundBodyKind => {BindingNamespace}.RequestBodyKind.{BinderEmitter.BodyKindName(boundType)};");

        // Rendered aside first: the array emitters answer "is there anything to declare?" only by
        // having written something, and the blank line separating the member from the one above it
        // has to come before that.
        var parameters = new StringBuilder();
        if (BinderEmitter.EmitParametersArray(parameters, boundType, indent, "s_synapseParameters"))
        {
            builder.AppendLine();
            builder.Append(parameters);
            builder.AppendLine();
            builder.AppendLine($"{indent}/// <inheritdoc />");
            builder.AppendLine(
                $"{indent}protected {modifier} global::System.Collections.Generic.IReadOnlyList<{InternalNamespace}.BoundParameterMetadata> DeclaredParameters()");
            builder.AppendLine($"{indent}{{");
            builder.AppendLine($"{indent}    return s_synapseParameters;");
            builder.AppendLine($"{indent}}}");
        }

        var formFields = new StringBuilder();
        if (BinderEmitter.EmitFormFieldsArray(formFields, boundType, indent, "s_synapseFormFields"))
        {
            builder.AppendLine();
            builder.Append(formFields);
            builder.AppendLine();
            builder.AppendLine($"{indent}/// <inheritdoc />");
            builder.AppendLine(
                $"{indent}protected {modifier} global::System.Collections.Generic.IReadOnlyList<{InternalNamespace}.FormFieldMetadata> DeclaredFormFields()");
            builder.AppendLine($"{indent}{{");
            builder.AppendLine($"{indent}    return s_synapseFormFields;");
            builder.AppendLine($"{indent}}}");
        }
    }

    /// <summary>
    ///     Renders the <c>CreateMetadata</c> override that <c>MapEndpoint&lt;TEndpoint&gt;()</c> reads.
    /// </summary>
    /// <remarks>
    ///     Always emitted, even when the endpoint carries no route attribute: the member is abstract on
    ///     <c>SynapseEndpoint</c>, so omitting it would leave the endpoint unimplemented. Empty verbs and
    ///     an empty route are the honest answer for an endpoint that declares its route inside
    ///     <c>Configure</c>, which the generator cannot see — the builder supplies both at startup.
    /// </remarks>
    private static void EmitCreateMetadata(StringBuilder builder,
        EndpointTarget endpoint,
        string indent,
        string modifier)
    {
        // The HTTP method and route come from attribute text the analyzer does not control, so they
        // are rendered through Roslyn's own literal escaper rather than interpolated straight into a
        // C# string literal — a route containing a quote or backslash would otherwise produce invalid
        // (or, worse, structurally different) generated code.
        var methods = endpoint.HttpMethod.Length == 0
            ? "global::System.Array.Empty<string>()"
            : $"new[] {{ {SymbolDisplay.FormatLiteral(endpoint.HttpMethod, quote: true)} }}";

        var route = SymbolDisplay.FormatLiteral(endpoint.Route, quote: true);

        var group = endpoint.GroupFullName is null
            ? string.Empty
            : $", typeof({endpoint.GroupFullName}), static () => new {endpoint.GroupFullName}()";

        builder.AppendLine($"{indent}/// <inheritdoc />");
        builder.AppendLine($"{indent}protected {modifier} {EndpointsNamespace}.EndpointMetadata CreateMetadata()");
        builder.AppendLine($"{indent}{{");
        builder.AppendLine($"{indent}    return new {EndpointsNamespace}.EndpointMetadata({methods}, {route}{group});");
        builder.AppendLine($"{indent}}}");
    }
}
