using System.Text;
using Microsoft.CodeAnalysis.Text;
using UnambitiousFx.Synapse.Endpoints.Generator.Model;

namespace UnambitiousFx.Synapse.Endpoints.Generator.Emit;

/// <summary>
///     Renders <c>SynapseEndpointGroup.g.cs</c>: the <c>IEndpointGroup</c> implementation that maps
///     every discovered endpoint.
/// </summary>
internal static class EndpointGroupEmitter
{
    internal static SourceText EmitGroup(string rootNamespace,
        EndpointTarget[] endpoints)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        // MapEndpoint<T>() is called below as an unqualified extension method. Extension method
        // lookup is scoped per source file, not by namespace nesting, so a consumer whose root
        // namespace is not itself nested under UnambitiousFx.Synapse.Endpoints needs this using —
        // without it, the call fails to resolve (CS1061) for any real consumer project. The
        // generator's own tests missed this because their fallback root namespace
        // ("UnambitiousFx.Synapse.Endpoints.Generated", used when build_property.RootNamespace is
        // unset) happens to be a child namespace of UnambitiousFx.Synapse.Endpoints, which makes the
        // extension method resolve by namespace-nesting coincidence alone.
        builder.AppendLine("using UnambitiousFx.Synapse.Endpoints;");
        builder.AppendLine();
        builder.AppendLine($"namespace {rootNamespace};");
        builder.AppendLine();
        builder.AppendLine("/// <summary>Maps every Synapse endpoint declared in this assembly.</summary>");
        builder.AppendLine("public sealed class SynapseEndpointGroup : global::UnambitiousFx.Synapse.Endpoints.IEndpointGroup");
        builder.AppendLine("{");
        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine("    public void Map(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints)");
        builder.AppendLine("    {");

        foreach (var endpoint in endpoints)
        {
            builder.AppendLine($"        endpoints.MapEndpoint<{endpoint.EndpointFullName}>();");
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        return SourceText.From(builder.ToString(), Encoding.UTF8);
    }
}
