using JetBrains.Annotations;
using Microsoft.CodeAnalysis;
using UnambitiousFx.Synapse.Generator.Analyzers;

namespace UnambitiousFx.Synapse.Generator.Tests.Analyzers;

[TestSubject(typeof(UnattributedHandlerAnalyzer))]
public sealed class UnattributedHandlerAnalyzerTests
{
    private const string Attributed = """
        public sealed record FirstRequest : IRequest;

        [RequestHandler<FirstRequest>]
        public sealed class FirstHandler : IRequestHandler<FirstRequest>
        {
            public ValueTask<Result> HandleAsync(FirstRequest request, CancellationToken ct = default)
                => ValueTask.FromResult(Result.Success());
        }

        """;

    private const string Unattributed = """
        public sealed record SecondRequest : IRequest;

        public sealed class SecondHandler : IRequestHandler<SecondRequest>
        {
            public ValueTask<Result> HandleAsync(SecondRequest request, CancellationToken ct = default)
                => ValueTask.FromResult(Result.Success());
        }
        """;

    [Fact]
    public async Task Analyze_WithAnUnattributedHandlerNextToAnAttributedOne_ReportsSyn104OnTheUnattributedClass()
    {
        // Arrange (Given)
        var source = AnalyzerTestHelper.Preamble + Attributed + Unattributed;

        // Act (When)
        var diagnostics = await AnalyzerTestHelper.RunAsync<UnattributedHandlerAnalyzer>(source);

        // Assert (Then)
        var diagnostic = Assert.Single(diagnostics);
        Assert.Equal("SYN104", diagnostic.Id);
        Assert.Equal(DiagnosticSeverity.Warning, diagnostic.Severity);
        Assert.Contains("SecondHandler", diagnostic.GetMessage());
    }

    [Fact]
    public async Task Analyze_WithNoAttributedHandlerAtAll_ReportsNothing()
    {
        // Arrange (Given)
        // an assembly that registers by hand is not using the generator
        var source = AnalyzerTestHelper.Preamble + Unattributed;

        // Act (When)
        var diagnostics = await AnalyzerTestHelper.RunAsync<UnattributedHandlerAnalyzer>(source);

        // Assert (Then)
        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task Analyze_WithEveryHandlerAttributed_ReportsNothing()
    {
        // Arrange (Given)
        var source = AnalyzerTestHelper.Preamble + Attributed;

        // Act (When)
        var diagnostics = await AnalyzerTestHelper.RunAsync<UnattributedHandlerAnalyzer>(source);

        // Assert (Then)
        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task Analyze_WithAnUnattributedEventHandler_ReportsSyn104()
    {
        // Arrange (Given)
        var source = AnalyzerTestHelper.Preamble + Attributed + """
            public sealed record PingEvent : IEvent;

            public sealed class PingHandler : IEventHandler<PingEvent>
            {
                public ValueTask<Result> HandleAsync(PingEvent @event, CancellationToken ct = default)
                    => ValueTask.FromResult(Result.Success());
            }
            """;

        // Act (When)
        var diagnostics = await AnalyzerTestHelper.RunAsync<UnattributedHandlerAnalyzer>(source);

        // Assert (Then)
        var diagnostic = Assert.Single(diagnostics);
        Assert.Contains("PingHandler", diagnostic.GetMessage());
    }

    [Fact]
    public async Task Analyze_WithAnAbstractUnattributedHandlerBase_ReportsNothing()
    {
        // Arrange (Given)
        var source = AnalyzerTestHelper.Preamble + Attributed + """
            public sealed record ThirdRequest : IRequest;

            public abstract class HandlerBase : IRequestHandler<ThirdRequest>
            {
                public abstract ValueTask<Result> HandleAsync(ThirdRequest request, CancellationToken ct = default);
            }
            """;

        // Act (When)
        var diagnostics = await AnalyzerTestHelper.RunAsync<UnattributedHandlerAnalyzer>(source);

        // Assert (Then)
        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task Analyze_WithAnUnattributedHandlerInGeneratedCode_ReportsNothing()
    {
        // Arrange (Given)
        var source = "// <auto-generated/>\n" + AnalyzerTestHelper.Preamble + Attributed + Unattributed;

        // Act (When)
        var diagnostics = await AnalyzerTestHelper.RunAtPathAsync<UnattributedHandlerAnalyzer>(source, "Handlers.g.cs");

        // Assert (Then)
        Assert.Empty(diagnostics);
    }
}
