<Project Sdk="Microsoft.NET.Sdk.Web">


    <ItemGroup>
        <ProjectReference Include="..\..\src\Synapse.AspNetCore\Synapse.AspNetCore.csproj" />
        <ProjectReference Include="..\..\src\Synapse\Synapse.csproj" />
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="WebApi.Tests" />
    </ItemGroup>


</Project>
