<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(LibraryTargetFrameworks)</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Synapse\Synapse.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="UnambitiousFx.Functional.AspNetCore" />
    </ItemGroup>

</Project>
