namespace UnambitiousFx.Synapse.Abstractions;

/// <summary>
///     Provides a contract for registering event dispatcher delegates for NativeAOT compatibility.
///     Implementations of this interface are typically generated by the Synapse.Generator.
/// </summary>
public interface IEventDispatcherRegistration
{
    /// <summary>
    ///     Registers event dispatcher delegates for all event types in the assembly.
    /// </summary>
    /// <param name="register">A callback to register each event type with its dispatcher delegate.</param>
    void RegisterDispatchers(Action<Type, Delegate> register);
}